<a href="https://colab.research.google.com/github/RahmadHadhiWicaksono/Kuliah/blob/main/Klasifikasi_data_tenaga_kesejahteraan_sosial_masyarakat_dengan_Decesion_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd
from sklearn import tree

In [36]:
DataSet = pd.read_csv('data-tenaga-kesejahteraan-sosial-masyarakat.csv',delimiter=',', header =0)
DataSet["keterangan"] = pd.factorize(DataSet.keterangan)[0]

In [37]:
DataSet = DataSet.drop(labels="nama", axis=1)
DataSet = DataSet.drop(labels="kecamatan", axis=1)
DataSet = DataSet.drop(labels="kabupaten", axis=1)
DataSet = DataSet.to_numpy()


In [38]:
print(DataSet)

[[  25 3000    0]
 [  30 2500    1]
 [  35 5000    1]
 [  33 5500    1]
 [  21 3050    1]
 [  26 5500    0]
 [  28 2500    1]
 [  27 5500    1]
 [  24 5500    1]
 [  26 3050    0]
 [  23 2500    0]
 [  31 5000    0]
 [  33 5500    0]
 [  36 2500    1]
 [  41 3050    1]
 [  51 5500    0]
 [  22 2500    0]
 [  41 5500    1]
 [  44 5000    0]
 [  39 5500    0]
 [  36 2500    1]
 [  33 3050    0]
 [  37 5500    1]
 [  34 5000    1]
 [  31 5500    1]
 [  28 2500    0]
 [  29 3050    1]
 [  26 5000    1]
 [  25 5500    1]
 [  24 3050    0]
 [  50 5500    0]
 [  27 3050    0]
 [  25 2500    0]
 [  41 5500    0]
 [  44 5000    1]
 [  39 5500    1]
 [  36 3050    0]
 [  33 3050    0]
 [  37 5500    0]
 [  34 2500    1]
 [  24 3050    0]
 [  26 2500    1]
 [  23 5000    1]
 [  31 3050    0]]


In [39]:
dataTraining = np.concatenate((DataSet[0:20,:],
                              DataSet[25:40,:]),axis = 0)
dataTesting = np.concatenate((DataSet[20:25,:],
                              DataSet[40:45,:]),axis = 0)

In [42]:
inputTraining = dataTraining[:,0:2]
inputTesting = dataTesting[:,0:2]
labelTraining = dataTraining[:,2]
labelTesting = dataTesting[:,2]

In [43]:
model = tree.DecisionTreeClassifier()
#mentrail model
model = model.fit(inputTraining, labelTraining)
#memprediksikan imput data testing
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya",labelTesting)
print("hasil prediksi: ",hasilPrediksi)
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi benar:",prediksiBenar,"data")
print("Prediksi salah:",prediksiSalah,"data")
print("akurasi: ",prediksiBenar/(prediksiBenar+prediksiSalah)*100,"%")

label sebenarnya [1 0 1 1 1 0 1 1 0]
hasil prediksi:  [1 0 0 1 0 0 0 0 1]
Prediksi benar: 4 data
Prediksi salah: 5 data
akurasi:  44.44444444444444 %
