<a href="https://colab.research.google.com/github/RahmadHadhiWicaksono/Kuliah/blob/main/Salinan_dari_Tugas_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('DataMHS.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)

[['PEREMPUAN' 28.0 3.07]
 ['PEREMPUAN' 32.0 3.17]
 ['PEREMPUAN' 29.0 3.54]
 ['PEREMPUAN' 27.0 3.41]
 ['PEREMPUAN' 29.0 3.09]
 ['LAKI - LAKI' 27.0 3.07]
 ['PEREMPUAN' 26.0 3.06]
 ['PEREMPUAN' 27.0 2.91]
 ['PEREMPUAN' 25.0 nan]
 ['PEREMPUAN' 28.0 2.2]
 ['PEREMPUAN' 27.0 3.44]
 ['PEREMPUAN' 32.0 2.4]
 ['PEREMPUAN' 26.0 2.45]
 ['PEREMPUAN' 31.0 2.57]
 ['PEREMPUAN' 26.0 nan]
 ['LAKI - LAKI' 27.0 3.04]
 ['PEREMPUAN' 27.0 3.19]
 ['LAKI - LAKI' nan 2.95]
 ['LAKI - LAKI' 27.0 2.11]
 ['LAKI - LAKI' 27.0 3.38]
 ['LAKI - LAKI' 28.0 3.29]
 ['LAKI - LAKI' 26.0 3.19]
 ['LAKI - LAKI' 26.0 3.11]
 ['LAKI - LAKI' 29.0 3.2]
 ['LAKI - LAKI' 25.0 3.09]
 ['LAKI - LAKI' 30.0 nan]
 ['LAKI - LAKI' 32.0 2.32]
 ['PEREMPUAN' 27.0 3.23]
 ['LAKI - LAKI' 27.0 3.52]
 ['LAKI - LAKI' 25.0 3.25]
 ['LAKI - LAKI' 32.0 2.86]
 ['LAKI - LAKI' 27.0 3.07]
 ['LAKI - LAKI' 25.0 3.07]
 ['LAKI - LAKI' 28.0 3.24]
 ['LAKI - LAKI' 32.0 3.2]
 ['PEREMPUAN' 27.0 3.15]
 ['PEREMPUAN' 32.0 3.36]
 ['PEREMPUAN' 27.0 3.6]
 ['LAKI - LAKI' 30.0 

In [ ]:
print(y)

['TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TEPAT' 'TEPAT' 'TEPAT'
 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT'
 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT' 'TEPAT'
 'TEPAT']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:3])
x[:,2:3] = imputer.transform(x[:, 2:3])

In [ ]:
print(x)

[['PEREMPUAN' 28.0 3.07]
 ['PEREMPUAN' 32.0 3.17]
 ['PEREMPUAN' 29.0 3.54]
 ['PEREMPUAN' 27.0 3.41]
 ['PEREMPUAN' 29.0 3.09]
 ['LAKI - LAKI' 27.0 3.07]
 ['PEREMPUAN' 26.0 3.06]
 ['PEREMPUAN' 27.0 2.91]
 ['PEREMPUAN' 25.0 3.1045652173913045]
 ['PEREMPUAN' 28.0 2.2]
 ['PEREMPUAN' 27.0 3.44]
 ['PEREMPUAN' 32.0 2.4]
 ['PEREMPUAN' 26.0 2.45]
 ['PEREMPUAN' 31.0 2.57]
 ['PEREMPUAN' 26.0 3.1045652173913045]
 ['LAKI - LAKI' 27.0 3.04]
 ['PEREMPUAN' 27.0 3.19]
 ['LAKI - LAKI' nan 2.95]
 ['LAKI - LAKI' 27.0 2.11]
 ['LAKI - LAKI' 27.0 3.38]
 ['LAKI - LAKI' 28.0 3.29]
 ['LAKI - LAKI' 26.0 3.19]
 ['LAKI - LAKI' 26.0 3.11]
 ['LAKI - LAKI' 29.0 3.2]
 ['LAKI - LAKI' 25.0 3.09]
 ['LAKI - LAKI' 30.0 3.1045652173913045]
 ['LAKI - LAKI' 32.0 2.32]
 ['PEREMPUAN' 27.0 3.23]
 ['LAKI - LAKI' 27.0 3.52]
 ['LAKI - LAKI' 25.0 3.25]
 ['LAKI - LAKI' 32.0 2.86]
 ['LAKI - LAKI' 27.0 3.07]
 ['LAKI - LAKI' 25.0 3.07]
 ['LAKI - LAKI' 28.0 3.24]
 ['LAKI - LAKI' 32.0 3.2]
 ['PEREMPUAN' 27.0 3.15]
 ['PEREMPUAN' 32.0 3.36]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [ ]:
print(x)

[[0.0 1.0 28.0 3.07]
 [0.0 1.0 32.0 3.17]
 [0.0 1.0 29.0 3.54]
 [0.0 1.0 27.0 3.41]
 [0.0 1.0 29.0 3.09]
 [1.0 0.0 27.0 3.07]
 [0.0 1.0 26.0 3.06]
 [0.0 1.0 27.0 2.91]
 [0.0 1.0 25.0 3.1045652173913045]
 [0.0 1.0 28.0 2.2]
 [0.0 1.0 27.0 3.44]
 [0.0 1.0 32.0 2.4]
 [0.0 1.0 26.0 2.45]
 [0.0 1.0 31.0 2.57]
 [0.0 1.0 26.0 3.1045652173913045]
 [1.0 0.0 27.0 3.04]
 [0.0 1.0 27.0 3.19]
 [1.0 0.0 nan 2.95]
 [1.0 0.0 27.0 2.11]
 [1.0 0.0 27.0 3.38]
 [1.0 0.0 28.0 3.29]
 [1.0 0.0 26.0 3.19]
 [1.0 0.0 26.0 3.11]
 [1.0 0.0 29.0 3.2]
 [1.0 0.0 25.0 3.09]
 [1.0 0.0 30.0 3.1045652173913045]
 [1.0 0.0 32.0 2.32]
 [0.0 1.0 27.0 3.23]
 [1.0 0.0 27.0 3.52]
 [1.0 0.0 25.0 3.25]
 [1.0 0.0 32.0 2.86]
 [1.0 0.0 27.0 3.07]
 [1.0 0.0 25.0 3.07]
 [1.0 0.0 28.0 3.24]
 [1.0 0.0 32.0 3.2]
 [0.0 1.0 27.0 3.15]
 [0.0 1.0 32.0 3.36]
 [0.0 1.0 27.0 3.6]
 [1.0 0.0 30.0 2.63]
 [1.0 0.0 26.0 3.39]
 [1.0 0.0 29.0 3.1045652173913045]
 [1.0 0.0 27.0 2.63]
 [0.0 1.0 32.0 3.63]
 [1.0 0.0 27.0 3.59]
 [1.0 0.0 26.0 3.64]
 [0.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state =1)

In [ ]:
print(x_train)

[[1.0 0.0 25.0 3.07]
 [1.0 0.0 26.0 3.39]
 [1.0 0.0 26.0 3.19]
 [0.0 1.0 32.0 3.36]
 [1.0 0.0 27.0 3.38]
 [0.0 1.0 32.0 3.63]
 [1.0 0.0 25.0 2.89]
 [1.0 0.0 32.0 2.32]
 [1.0 0.0 26.0 3.11]
 [0.0 1.0 31.0 2.57]
 [1.0 0.0 27.0 2.63]
 [1.0 0.0 nan 2.95]
 [0.0 1.0 29.0 3.8]
 [1.0 0.0 25.0 3.09]
 [1.0 0.0 29.0 3.2]
 [0.0 1.0 29.0 3.09]
 [1.0 0.0 28.0 3.24]
 [0.0 1.0 26.0 3.1045652173913045]
 [1.0 0.0 32.0 2.86]
 [0.0 1.0 27.0 3.44]
 [1.0 0.0 27.0 3.52]
 [1.0 0.0 26.0 3.64]
 [1.0 0.0 32.0 3.2]
 [1.0 0.0 27.0 2.11]
 [1.0 0.0 28.0 3.29]
 [1.0 0.0 30.0 3.1045652173913045]
 [0.0 1.0 26.0 3.06]
 [0.0 1.0 27.0 2.91]
 [0.0 1.0 nan 3.69]
 [0.0 1.0 32.0 3.17]
 [0.0 1.0 27.0 3.19]
 [0.0 1.0 28.0 3.07]
 [1.0 0.0 27.0 3.04]
 [1.0 0.0 27.0 3.07]
 [0.0 1.0 32.0 2.4]
 [0.0 1.0 28.0 2.2]
 [0.0 1.0 25.0 3.1045652173913045]
 [0.0 1.0 26.0 2.45]
 [1.0 0.0 27.0 3.59]
 [0.0 1.0 27.0 3.6]]


In [ ]:
print(x_test)

[[0.0 1.0 27.0 3.23]
 [0.0 1.0 27.0 3.15]
 [1.0 0.0 29.0 3.1045652173913045]
 [1.0 0.0 30.0 2.63]
 [0.0 1.0 29.0 3.54]
 [0.0 1.0 27.0 3.41]
 [1.0 0.0 25.0 3.37]
 [1.0 0.0 25.0 3.25]
 [0.0 1.0 42.0 2.75]
 [1.0 0.0 27.0 3.07]]


In [ ]:
print(y_train)

[0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1
 1 0 0]


In [ ]:
print(y_test)

[1 0 0 0 1 1 0 0 0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [ ]:
print(x_test)

[[0.0 1.0 27.0 0.3396506972314704]
 [0.0 1.0 27.0 0.1411806776511739]
 [1.0 0.0 29.0 0.02846265022649542]
 [1.0 0.0 30.0 -1.1488744496207521]
 [0.0 1.0 29.0 1.108722023105119]
 [0.0 1.0 27.0 0.7862082412871375]
 [1.0 0.0 25.0 0.6869732314969893]
 [1.0 0.0 25.0 0.3892682021265445]
 [0.0 1.0 42.0 -0.8511694202503074]
 [1.0 0.0 27.0 -0.05728934192912259]]


In [ ]:
print(x_test)

[[0.0 1.0 27.0 0.3396506972314704]
 [0.0 1.0 27.0 0.1411806776511739]
 [1.0 0.0 29.0 0.02846265022649542]
 [1.0 0.0 30.0 -1.1488744496207521]
 [0.0 1.0 29.0 1.108722023105119]
 [0.0 1.0 27.0 0.7862082412871375]
 [1.0 0.0 25.0 0.6869732314969893]
 [1.0 0.0 25.0 0.3892682021265445]
 [0.0 1.0 42.0 -0.8511694202503074]
 [1.0 0.0 27.0 -0.05728934192912259]]
